### ISSUE TITLE
Two minor grammar issues in Semith/Booty Call/Buttfuck [0.7.34]

### ISSUE THREAD

**Issue by Zsar** [OXOIndustries/TiTS-Public#12]
In includes/tavros/semith.as, function semithSexButtfuck, line 558:
"When [you are finally] spent, [...] badly abused as[s]"

Additionally, mayhap a matter of taste: "[- ]it comes free with an almost audible “pop”[ -]".

Complete paragraph:
"When finally you are spent, you withdraw your gently throbbing cock out of the little demon’s badly abused as (it comes free with an almost audible “pop”) and flop back onto a part of the sofa not plastered in cum, watching him with a glow of post-coital contentment as he slowly turns over, chest still heaving, and looks over at you with disbelief and gratification fighting for control of his narrow, handsome features."

**Comment by Jacques00** [comment]
Fixed for the next release.
