### ISSUE TITLE
Urbolg fixes

### ISSUE THREAD

**Issue by viriv** [OXOIndustries/TiTS-Public#163]
**typos**

https://github.com/OXOIndustries/TiTS-Public/blob/6e2ddd577060544a9fb440bc69a2ab444165c22b/includes/zhengShiStation/urbolg.as#L146
extra newlines seem pointless? unless I'm missing some output from generic losses/generate map?

\-----------------------------------------------------------------------------------------------------------------------

https://github.com/OXOIndustries/TiTS-Public/blob/6e2ddd577060544a9fb440bc69a2ab444165c22b/includes/zhengShiStation/urbolg.as#L378
transfer mispelled as trnsfer

\-----------------------------------------------------------------------------------------------------------------------

https://github.com/OXOIndustries/TiTS-Public/blob/6e2ddd577060544a9fb440bc69a2ab444165c22b/includes/zhengShiStation/urbolg.as#L418
think this is suppose to say "but" not "by"

\-----------------------------------------------------------------------------------------------------------------------

https://github.com/OXOIndustries/TiTS-Public/blob/6e2ddd577060544a9fb440bc69a2ab444165c22b/includes/zhengShiStation/urbolg.as#L476
bouder? should be boulder? not sure on this one

\-----------------------------------------------------------------------------------------------------------------------

https://github.com/OXOIndustries/TiTS-Public/blob/6e2ddd577060544a9fb440bc69a2ab444165c22b/includes/zhengShiStation/urbolg.as#L632
missing end of dialogue punctuation

> ‘Twas better than he deserved, the sneak, but it’s worth it to hear him clomp around on the deck”

\-----------------------------------------------------------------------------------------------------------------------

https://github.com/OXOIndustries/TiTS-Public/blob/6e2ddd577060544a9fb440bc69a2ab444165c22b/includes/zhengShiStation/urbolg.as#L807
missing ending punctuation

\-----------------------------------------------------------------------------------------------------------------------

https://github.com/OXOIndustries/TiTS-Public/blob/6e2ddd577060544a9fb440bc69a2ab444165c22b/includes/zhengShiStation/urbolg.as#L874-L877
Missing leading space for non herm branches

\-----------------------------------------------------------------------------------------------------------------------

https://github.com/OXOIndustries/TiTS-Public/blob/6e2ddd577060544a9fb440bc69a2ab444165c22b/includes/zhengShiStation/urbolg.as#L913
missing ending punctuation

\-----------------------------------------------------------------------------------------------------------------------

https://github.com/OXOIndustries/TiTS-Public/blob/6e2ddd577060544a9fb440bc69a2ab444165c22b/includes/zhengShiStation/urbolg.as#L960
missing ending punctuation

\-----------------------------------------------------------------------------------------------------------------------

https://github.com/OXOIndustries/TiTS-Public/blob/6e2ddd577060544a9fb440bc69a2ab444165c22b/includes/zhengShiStation/urbolg.as#L990
missing leading space

\-----------------------------------------------------------------------------------------------------------------------

https://github.com/OXOIndustries/TiTS-Public/blob/6e2ddd577060544a9fb440bc69a2ab444165c22b/includes/zhengShiStation/urbolg.as#L1315
layered /with/ droplets?
> uncaring that your [pc.lipsChaste] are layered droplets of his cum.

\-----------------------------------------------------------------------------------------------------------------------

https://github.com/OXOIndustries/TiTS-Public/blob/6e2ddd577060544a9fb440bc69a2ab444165c22b/includes/zhengShiStation/urbolg.as#L1320
missing ending punctuation

\-----------------------------------------------------------------------------------------------------------------------

https://github.com/OXOIndustries/TiTS-Public/blob/6e2ddd577060544a9fb440bc69a2ab444165c22b/includes/zhengShiStation/urbolg.as#L1669-L1673
lines 1670-1671 are missing the leading space, or 1669 is missing ending space
and line 1672 and 1673 are missing ending punctuation

\-----------------------------------------------------------------------------------------------------------------------

https://github.com/OXOIndustries/TiTS-Public/blob/6e2ddd577060544a9fb440bc69a2ab444165c22b/includes/zhengShiStation/urbolg.as#L1880
The space at the end of the line is an extra. All possible following lines already have a leading space.

\-----------------------------------------------------------------------------------------------------------------------

https://github.com/OXOIndustries/TiTS-Public/blob/6e2ddd577060544a9fb440bc69a2ab444165c22b/includes/zhengShiStation/urbolg.as#L1946

>  your stomach pressed against the cum you eft there earlier,

eft should be left
also shouldn't this have an if(pc.hasCock()) check to better fit with what happens in
https://github.com/OXOIndustries/TiTS-Public/blob/6e2ddd577060544a9fb440bc69a2ab444165c22b/includes/zhengShiStation/urbolg.as#L1902-L1917

\-----------------------------------------------------------------------------------------------------------------------

https://github.com/OXOIndustries/TiTS-Public/blob/6e2ddd577060544a9fb440bc69a2ab444165c22b/includes/zhengShiStation/urbolg.as#L2476-L2478
branches missing leading spaces or previous output missing ending space

\-----------------------------------------------------------------------------------------------------------------------

**bugfixes**

https://github.com/OXOIndustries/TiTS-Public/blob/6e2ddd577060544a9fb440bc69a2ab444165c22b/includes/zhengShiStation/urbolg.as#L1236-L1239
if x doesn't have a sheath or knot and pc has no balls/internal balls [pc.sack] defaults to prostate which doesn't fit the scene.
would reommend changing the else to an else if(pc.balls > 0) and either rewritting the scene for 0 balls or leaving it as is since the scene works by not mentioning it at all.

\-----------------------------------------------------------------------------------------------------------------------

https://github.com/OXOIndustries/TiTS-Public/blob/6e2ddd577060544a9fb440bc69a2ab444165c22b/includes/zhengShiStation/urbolg.as#L1555-L1559

"Cookies" event

if pc is korgonne race and neuter they get garbled text with single "Y's" instead of "your genitals" this occurs in multiple places during the scene. (1523-1545, 1547-1551)

would recommend adding around line 1482 
https://github.com/OXOIndustries/TiTS-Public/blob/6e2ddd577060544a9fb440bc69a2ab444165c22b/includes/zhengShiStation/urbolg.as#L1482
an
if(pc.race() == "korgonne " and !pc.hasGenitals()) addDisabledButton(0,"Cookies","Cookies");
else addButton(0,"Cookies",urbyCookiePCSnacks);

in order to prevent this but allow non-korgonne neuter pcs to still access the other scene
or could rewrite the scene but there are a few spots where the text gets garbled.

\-----------------------------------------------------------------------------------------------------------------------

This happens again in other pbcookie option, "Jizz" at
https://github.com/OXOIndustries/TiTS-Public/blob/6e2ddd577060544a9fb440bc69a2ab444165c22b/includes/zhengShiStation/urbolg.as#L1632-L1636

This doesn't have a race requirement this time so just doing a
if(!pc.hasGenitals()) addDisabledButton(1,"Jizz","Jizz");
else addButton(1,"Jizz",drinkYummyUrbolgCum); 
at
https://github.com/OXOIndustries/TiTS-Public/blob/6e2ddd577060544a9fb440bc69a2ab444165c22b/includes/zhengShiStation/urbolg.as#L1483
would suffice
and again could rewrite the scene this time.  There is only one place where the text gets garbled this time.

\-----------------------------------------------------------------------------------------------------------------------

"RideHisCock" Event
lots of references to pc.cock but neuters can get to this scene and the lack of checks for pc.hasCock() breaks the scene.  Problem doesn't occur if pc has vagina and no cock. Could do a check on the button if(!pc.hasGenitals()) addDisabledButton() sorta thing at
https://github.com/OXOIndustries/TiTS-Public/blob/6e2ddd577060544a9fb440bc69a2ab444165c22b/includes/zhengShiStation/urbolg.as#L765-L766

\-----------------------------------------------------------------------------------------------------------------------

https://github.com/OXOIndustries/TiTS-Public/blob/6e2ddd577060544a9fb440bc69a2ab444165c22b/includes/zhengShiStation/urbolg.as#L2447

> , your cock shaking and flexing while you suffer a massive dry orgasm

should have a pc.hasCock() check for neuters

\-----------------------------------------------------------------------------------------------------------------------

https://github.com/OXOIndustries/TiTS-Public/blob/6e2ddd577060544a9fb440bc69a2ab444165c22b/includes/zhengShiStation/urbolg.as#L2451

> " His giant knot moving around inside you grants the slightest of opportunities for cum to slowly drip from your half-hard cock, bouncing against his stomach with dull splatters. Honestly, you couldn’t care less right now"

should have a pc.hasCock() check for neuters

\-----------------------------------------------------------------------------------------------------------------------

https://github.com/OXOIndustries/TiTS-Public/blob/6e2ddd577060544a9fb440bc69a2ab444165c22b/includes/zhengShiStation/urbolg.as#L2456-L2457
The second branch here can never be reached as the first branch has same conditional
should probably be a pc.hasCock() instead

\-----------------------------------------------------------------------------------------------------------------------

**questionable?**

https://github.com/OXOIndustries/TiTS-Public/blob/6e2ddd577060544a9fb440bc69a2ab444165c22b/includes/zhengShiStation/urbolg.as#L600
are watts capitalized? (This is stupidly minor whatever)

\-----------------------------------------------------------------------------------------------------------------------

https://github.com/OXOIndustries/TiTS-Public/blob/6e2ddd577060544a9fb440bc69a2ab444165c22b/includes/zhengShiStation/urbolg.as#L972
capitalize b in bout since this is the start of a sentence? starts with an apostrophe though? (I am not editor, but this struck me as odd)

\-----------------------------------------------------------------------------------------------------------------------

https://github.com/OXOIndustries/TiTS-Public/blob/6e2ddd577060544a9fb440bc69a2ab444165c22b/includes/zhengShiStation/urbolg.as#L1096
if this is the 3rd+ time getting this scene the ending mentions spending half and hour alone sucking.  More time should be processed maybe getting longer with each iteration of the event

\-----------------------------------------------------------------------------------------------------------------------

https://github.com/OXOIndustries/TiTS-Public/blob/6e2ddd577060544a9fb440bc69a2ab444165c22b/includes/zhengShiStation/urbolg.as#L1838
what's the point of this if? there's only one access to this function at
https://github.com/OXOIndustries/TiTS-Public/blob/6e2ddd577060544a9fb440bc69a2ab444165c22b/includes/zhengShiStation/urbolg.as#L342-L343
which has a check on the same flag already preventing users from accessing the scene with that flag set to anything but undefined.
defensive programming just in case, or a missed remnant from a refactor?

**Comment by Fenoxo** [comment]
Newlines before combat resolution are there at the end of every combat encounter to provide padding before the "You won the fight!" message.

Pretty much everything else has been addressed.

The final thing you mentioned - URBY_COLLAR_FUN - it doesn't prevent characters from accessing the scene. It simply changes the name of it. The first time, it's shown as "Collar". Afterward it appears as "Slave Collar".
