### ISSUE TITLE
Typo in Uveto Subtuner file (bettingAtTheTaurRaces function)

### ISSUE THREAD

**Issue by Somebody-Else-Entirely** [OXOIndustries/TiTS-Public#165]
<i>“You can head to our stadium seating up the stairs here and watch the race. When it’s concluded you can return here.”</i>");
		if(pc.isAss()) output("\n\nYou nod");
		else output("thank the woman");
		output(" and make your way towards the stairs,

If the pc is not an ass, the output is [return here."thank the woman and make your way towards the stairs,]

**Comment by Fenoxo** [comment]
Thanks! Fixt for next patch.
