### ISSUE TITLE
SUPPRESS_COMBAT still not functional (flags["KQ2_SUPPRESS_COMBAT"] != flags["SUPPRESS_COMBAT"])

### ISSUE THREAD

**Issue by Tyrn-11** [OXOIndustries/TiTS-Public#166]
Sorry for the late follow-up(I couldn't see what you changed exactly, since I couldn't see the source until the public release) but the issue has not been fixed.

This mostly because you where looking at the flags["KQ2_SUPPRESS_COMBAT"] and flags["SUPPRESS_COMBAT"] flags as if they where the same, which they aren't. The KQ2_ one works as intended, in the context of the kq2, where it's checked in kq2CombatSuppression. But kq2CombatSuppression is only called in the context of kq2 and only works there.

flags["SUPPRESS_COMBAT"] on the other hand is only ever set and never read. Not in 'events\kashimaIncident\roomfunctions.as' and not in 'uveto\roomFunctions.as'.

So combat suppression(with flags["SUPPRESS_COMBAT"]) is still very much broken.

_Originally posted by @Tyrn-11 in https://github.com/OXOIndustries/TiTS-Public/issues/142#issuecomment-449849656_

**Comment by Fenoxo** [comment]
Thanks for the heads up. I've converted the Kashima incident ones to KI_SUPPRESS_COMBAT and hooked a check into its combat proccing function.

The lone SUPPRESS_COMBAT on uveto has been adjusted to reset the uveto stepcounter, effectively accomplishing the same thing without additional variables.
