### ISSUE TITLE
Typo in the Halloween section

### ISSUE THREAD

**Issue by Marco-Polo-1** [OXOIndustries/TiTS-Public#193]
https://github.com/OXOIndustries/TiTS-Public/blob/76a4fc57d1021124e44cec3f3b37ba108f22afaa/includes/holidayEvents/halloweenCostumes.as#L1828

"your a Goddess" should be "YOU'RE a Goddess" I believe.

**Comment by Fenoxo** [comment]
Fixt for next patch.
