### ISSUE TITLE
Fadil 69 tooltip

### ISSUE THREAD

**Issue by SecoWWW** [OXOIndustries/TiTS-Public#204]
Hey in description of 69 scene there is a description error:
Error, invalid description for "CharName". Passed descrition call: "pussyNounComplex" with argument : "0"

**Comment by Fenoxo** [comment]
Thanks. Made some tweaks to the parsers for vaginal nouns to make those checks a valid description call.

**Comment by Fenoxo** [comment]
Will be handled next patch

**Comment by SecoWWW** [comment]
Yeah no problem, but found more errors like these in Xotchi scene. There were at least 4, I think. Didn't went through more of the new scenes.
