### ISSUE TITLE
Milodan Omega Oil Submition

### ISSUE THREAD

**Issue by SecoWWW** [OXOIndustries/TiTS-Public#245]
I clicked the submit button when starting fight with milodan.

[Uncaught TypeError]

Something bad happened!

Please report this message, and include any prior scene text or a description of what you did before seeing this message:

Flash Player: StandAlone - Windows 10
Flash Version: WIN 23,0,0,162
Game Version: 0.8.065

Error Name: TypeError
Error Mesg: Error #1009
TypeError: Error #1009
	at classes::TiTS/omegaLossToMiloMale()
	at classes::TiTS/buttonClick()

**Comment by Fenoxo** [comment]
This issue will be addressed in the forum bug reports
