### ISSUE TITLE
Possibly incorrect personality range in Myrellion DMZ dick-signing scene

### ISSUE THREAD

**Issue by PrincessRTFM** [OXOIndustries/TiTS-Public#250]
The generally-used ranges for personalities (as of the currently available public release, where the personality score ranges `[0, 100]`) are `[0, 33]` for kind, `[34, 66]` for mischievous, and `[67, 100]` for hard ([source](https://github.com/OXOIndustries/TiTS-Public/blob/d831c8805b8af9e0e31d30af20f74d018752b7db/classes/Creature.as#L4646-L4658)). However, in `includes/myrellion/roomFunctions.as`, [line 1493](https://github.com/OXOIndustries/TiTS-Public/blob/d831c8805b8af9e0e31d30af20f74d018752b7db/includes/myrellion/roomFunctions.as#L1493) uses 90 for the lower bound of a hard personality, and [line 1506](https://github.com/OXOIndustries/TiTS-Public/blob/d831c8805b8af9e0e31d30af20f74d018752b7db/includes/myrellion/roomFunctions.as#L1506) uses 10 as the upper bound for nice. The [last time those lines appear to have been touched](https://github.com/OXOIndustries/TiTS-Public/blame/d831c8805b8af9e0e31d30af20f74d018752b7db/includes/myrellion/roomFunctions.as#L1493) is in 2017, so if it is not intentional, that may be why it's wrong.

**Comment by Fenoxo** [comment]
Fixt
