### ISSUE TITLE
Incorrect condition in slyveren slavebreaker victory scene

### ISSUE THREAD

**Issue by PrincessRTFM** [OXOIndustries/TiTS-Public#251]
In `includes/zhengShiStation/slyverenSlavebreaker.as`, [line 1150](https://github.com/OXOIndustries/TiTS-Public/blob/d831c8805b8af9e0e31d30af20f74d018752b7db/includes/zhengShiStation/slyverenSlavebreaker.as#L1150) incorrectly checks if the PC has a cock at all instead of whether it is exposed. [Line 1160](https://github.com/OXOIndustries/TiTS-Public/blob/d831c8805b8af9e0e31d30af20f74d018752b7db/includes/zhengShiStation/slyverenSlavebreaker.as#L1160) uses the correct condition, for comparison.

**Comment by Fenoxo** [comment]
Fixt.
