### ISSUE TITLE
Wrong target in slyveren slavebreaker throbb scene

### ISSUE THREAD

**Issue by PrincessRTFM** [OXOIndustries/TiTS-Public#252]
In `includes/zhengShiStation/slyverenSlavebreaker.as`, giving a defeated slavebreaker additional throbb (from the player's own inventory supply) checks the slavebreaker's ball fullness (`if(enemy.ballFullness < 100)`) but sets the PC's instead (`pc.ballFullness = 100`) on [line 1448](https://github.com/OXOIndustries/TiTS-Public/blob/d831c8805b8af9e0e31d30af20f74d018752b7db/includes/zhengShiStation/slyverenSlavebreaker.as#L1448).

**Comment by Fenoxo** [comment]
Fixt
