### ISSUE TITLE
Azra's morning-after scene uses the wrong condition

### ISSUE THREAD

**Issue by PrincessRTFM** [OXOIndustries/TiTS-Public#253]
After checking if the PC has more than one cock ([line 1761](https://github.com/OXOIndustries/TiTS-Public/blob/d831c8805b8af9e0e31d30af20f74d018752b7db/includes/follower/azra.as#L1761)), the exact same check is repeated on [line 1764](https://github.com/OXOIndustries/TiTS-Public/blob/d831c8805b8af9e0e31d30af20f74d018752b7db/includes/follower/azra.as#L1764). Given the text being output, I suspect it should instead be something like

```actionscript
if(pc.cockTotal() == 2) output("the other");
else output("another");
```

Also, tangentially related, the [`azrasStud()`](https://github.com/OXOIndustries/TiTS-Public/blob/d831c8805b8af9e0e31d30af20f74d018752b7db/includes/follower/azra.as#L118) and [`azraKnowsShePregnant()`](https://github.com/OXOIndustries/TiTS-Public/blob/d831c8805b8af9e0e31d30af20f74d018752b7db/includes/follower/azra.as#L122) functions have been hardcoded to return false since they were added in 2017. I can only assume that they are planned to eventually allow an expansion to Azra's content, especially since the relevant busts (such as `AZRA_PREG_NUDE`) do exist according to the `impulse` cheat - `showBust` with argument `"AZRA_PREG_NUDE"` successfully displays it. Unless that intended expansion has been canceled?

**Comment by Fenoxo** [comment]
Fixt!

Azra needs a whole expansion before any of that stuff could be developed.
