### ISSUE TITLE
Allow for best ending option in Federation Quest

### ISSUE THREAD

**Issue by MostlyThere256** [OXOIndustries/TiTS-Public#257]
Currently, this option is blocked off, because ships weren't implemented at that point in time. Now that they are, it's high time this option becomes available.

https://github.com/OXOIndustries/TiTS-Public/blob/d831c8805b8af9e0e31d30af20f74d018752b7db/includes/events/federationQuest/federationQuest.as#L1819

**Comment by MostlyThere256** [comment]
#258 has been created, allowing for the best option to be selectable, if the PC has a crew capacity for at least 12, or if the 'clowncar' cheat has been activated.

**Comment by Fenoxo** [comment]
That check is meant for if you have a capital ship sized vessel, not a 12 man truck. However I have updated it to check against the capacity system, so it should be futureproofed.
