### ISSUE TITLE
Codex improvement (Xenogen SynthSheath)

### ISSUE THREAD

**Issue by Syltan-Adam** [OXOIndustries/TiTS-Public#3]
**Item: Xenogen Biotech SynthSheath
The XenoGen Biotech SynthSheath was a prototypical effort in their genital modification program.**
This working can be improved with:
-Proper Formatting with spaces
-Manufactured by

**Comment by Fenoxo** [comment]
Wat

**Comment by Syltan-Adam** [comment]
XD Here, I'll help you out a tiny bit. This is the issue that I noted.
![image](https://cloud.githubusercontent.com/assets/7786316/21747158/49f20a7a-d52c-11e6-9fc6-6b3da89c38ab.png)
Proper
![image](https://cloud.githubusercontent.com/assets/7786316/21747160/5694b66a-d52c-11e6-8a5e-b06942f074b5.png)

**Comment by Jacques00** [comment]
Made some edits so this will be corrected in the next build.
