### ISSUE TITLE
This line has the wrong Preg flag or whatever, being for Tam-Tam instead of Khorgan. 

### ISSUE THREAD

**Issue by Marco-Polo-1** [OXOIndustries/TiTS-Public#45]
The problem with this line is that it features a flag check for the wrong girl. Should be ["KHORGAN_GAST_PREG_TIMER"], but instead is ["TAMTAM_GAST_PREG_TIMER"]. Simple enough to fix.

https://github.com/OXOIndustries/TiTS-Public/blob/193db15a7b922869d54abe7c466f2e1684734fb2/includes/gastigoth/gastigoth.as#L1409

**Comment by Fenoxo** [comment]
Fixt.
