### ISSUE TITLE
Chaurmine intimate catch

### ISSUE THREAD

**Issue by SecoWWW** [OXOIndustries/TiTS-Public#55]
thankful that his claws are apparently too wet and lubed up by your girl-cum juices to cause harm or discomfort; instead, his claws and scales have just enough of an edge to stimulate your inner walls with the most lascivious friction. On the verge of a toe-curling high, you cry out in distress when he slides out of your cunt, the mind blowing friction gone as he brings his [Uncaught TypeError]

Something bad happened!

Please report this message, and include any prior scene text or a description of what you did before seeing this message:

Flash Player: StandAlone - Windows 7
Flash Version: WIN 23,0,0,162
Game Version: 0.7.136

Error Name: TypeError
Error Mesg: Error #1010
TypeError: Error #1010
	at classes::TiTS/intimateCatchChaurmine()
	at classes::TiTS/buttonClick()

(Access the main menu to start a new game or use the data menu to load a previously saved game. The buttons are located in the lower left of the game screen.)

i just played, went from New Texas to Uveto

**Comment by Fenoxo** [comment]
Hey is this still happening or did we get it cleaned up at some point? The code looks fine and I had no issue with my vagina-having PC completing the scene.

**Comment by Fenoxo** [comment]
Whoops, meant to just comment!

**Comment by SecoWWW** [comment]
Well it never happened since then, so you can probably close it. Maybe just some mem-leak.
