### ISSUE TITLE
Kase evict boots any sleep mate

### ISSUE THREAD

**Issue by virlh** [OXOIndustries/TiTS-Public#60]
If kase is evicted from ship crew whoever is currently being slept with is removed and must be asked again
https://github.com/OXOIndustries/TiTS-Public/blob/6c503c8edaa513b2d4f0e72677f0b3a1ddf0eff9/includes/follower/kase.as#L952

suggested edit: check if Kase is current sleep mate before removing member 

if(flags["CREWMEMBER_SLEEP_WITH"] == "KASE") flags["CREWMEMBER_SLEEP_WITH"] = undefined;

**Comment by Fenoxo** [comment]
Got it. Thanks!
