### ISSUE TITLE
Stormguard first victory leave option does not set honor

### ISSUE THREAD

**Issue by virlh** [OXOIndustries/TiTS-Public#61]
Defeating the Stormguard on your first encounter and selecting to simply leave will keep the flags["STORMGUARD_HONOR"] value as undefined.  The next time he is encountered the stormguardhonor function at line 109 catches that and assigns it 0.  So the code starting at line 123 is run and he mocks the player for being defeated and will refuse to challenge them despite the player winning their only encounter with him so far.

simple suggested fix is to change the value assigned to undefined honors in the stormguardhonor function to 1 from 0
https://github.com/OXOIndustries/TiTS-Public/blob/6c503c8edaa513b2d4f0e72677f0b3a1ddf0eff9/includes/uveto/stormguardMale.as#L66

or alternatively call stormguardhonor(1) in the pcWinsVsSG() and remove stormguardhonor(1) function calls in the sex functions that can be used in pcWinsVsSG() could cause issues if the sex functions are called from somewhere else other than the victory screen and need to change the honor value or if an option is added to the victory screen that should subtract honor.

**Comment by virlh** [comment]
First victory* not fist victory

**Comment by Fenoxo** [comment]
Went ahead and did the first fix. Thanks.
