### ISSUE TITLE
Kase apartment missing npc flag when evicted from crew

### ISSUE THREAD

**Issue by virlh** [OXOIndustries/TiTS-Public#62]
Kase's apartment tile on tavros does not update with an npc flag when he is inside after being evicted

![kase](https://user-images.githubusercontent.com/35020262/36722563-d7b1731e-1b7b-11e8-9c4c-2c543921eeb3.jpg)

adding

```
if(flags["KASE_CREW"] == 0) rooms["RESIDENTIAL DECK KASES APARTMENT"].addFlag(GLOBAL.NPC);
else rooms["RESIDENTIAL DECK KASES APARTMENT"].removeFlag(GLOBAL.NPC); 
```
to the variableRoomUpdateCheck() in game.as should fix this as flags["KASE_CREW"] can only be set to 0 after he has been evicted.  It is left undefined if he never joins and should not set the npc flag for his apartment then.

**Comment by Fenoxo** [comment]
Fixt! Got it.
