### ISSUE TITLE
Error in the conditions for Birthing on Mhen'ga

### ISSUE THREAD

**Issue by Marco-Polo-1** [OXOIndustries/TiTS-Public#63]
https://github.com/OXOIndustries/TiTS-Public/blob/0fa4f296ea19d34bfbc0f9c33af598c29a5b29da/includes/mhenga/zilMale.as#L1388

Correct me if I'm wrong but the code syntax seems to be saying lit. "If planet name is NOT Mhen'ga". Am I correct? If so, this seems like a bug. Just saying.

**Comment by Fenoxo** [comment]
Fixt for next patch.
