### ISSUE TITLE
follower.anno small issues

### ISSUE THREAD

**Issue by cascet** [OXOIndustries/TiTS-Public#7]
line 2839: part after first sentence should be in if-clause
line 3072: "arace" -> "racing"
line 3221: "throb" not conjugated

**Comment by Fenoxo** [comment]
"Spreading her cheeks wide to ease your entrance, you let your [pc.tailCock] press against her sphincter."

...why should that be in an if-clause?

The other typos have been fixed in the private repo.

**Comment by cascet** [comment]
I mean the rest of the line, not just this sentence. It is very similar to the other part in the else statement (line 2847).

**Comment by Fenoxo** [comment]
Ah, good call. Fixt.
