### ISSUE TITLE
Crit bonuses are broken

### ISSUE THREAD

**Issue by Alceris** [OXOIndustries/TiTS-Public#73]
Both melee and ranged weapons benefit from the ranged weapon's crit bonus, unless the player has the Linked Emitters perk, in which case the ranged weapon's crit bonus is unused.

**Comment by Fenoxo** [comment]
Fixed for next backer build. Thanks!

**Comment by Fenoxo** [comment]
(Also got the bug where it wasn't properly making sure you had shields active.
