### ISSUE TITLE
annoSexed() breaks haveFuckedAnno()

### ISSUE THREAD

**Issue by Tyrn-11** [OXOIndustries/TiTS-Public#74]
annoSexed() has this line:
`if(flags["ANNO_SEXED"] == undefined) flags["ANNO_SEXED"] = 0;`
After this code is executed, the flag is no longer undefined, so this code:
`if (flags["ANNO_SEXED"] == undefined) return false;`
in haveFuckedAnno() will never have it's condition fullfilled.
haveFuckedAnno() will always return true after the first call to annoSexed().
Changing the check to
`if (flags["ANNO_SEXED"] == undefined || flags["ANNO_SEXED"] == 0)`
should fix this.
This has been broken for a long time, I think the last modifications to that code where sometime in 2014 and I only stumbled upon this by chance.

**Comment by Fenoxo** [comment]
Thanks. I got it fixed now for the next patch.
